import {all,put,stampBase} from './db.js?v=0.13.0';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeCardImage(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}}
let query='',domain='';
export async function mountCardLibrary(root,api){
 const cards=(await all('notes')).filter(n=>n.record_type==='library_card'&&!n.archived&&!n.deleted_at).sort((a,b)=>a.name.localeCompare(b.name));
 root.innerHTML=`<header class="collection-head library-heading"><div><span class="eyebrow">THE CARD ARCHIVE · PERSONAL COLLECTION</span><h2>Study the details.</h2><p>Keep the cards you’re testing close. Images, interactions, and questions in one place.</p></div><button type="button" class="btn primary" id="cardAdd">+ Add card</button></header><div class="archive-controls"><label><span class="label-title">Search your collection</span><input type="search" id="cardSearch" placeholder="Card name, set, or notes" value="${esc(query)}"></label><label><span class="label-title">Domain / category</span><select id="cardDomain"><option value="">All categories</option>${[...new Set(cards.map(c=>c.domain).filter(Boolean))].sort().map(d=>`<option ${d===domain?'selected':''}>${esc(d)}</option>`).join('')}</select></label><span id="cardCount" class="archive-count"></span></div><div id="cardGallery" class="card-gallery"></div><p class="archive-footnote">Your own research collection. Add cards and HTTPS image links; this is not an automatically updated full-set database.</p>`;
 const gallery=root.querySelector('#cardGallery');
 function draw(){const shown=cards.filter(c=>(!domain||c.domain===domain)&&[c.name,c.set,c.text].join(' ').toLowerCase().includes(query.toLowerCase()));root.querySelector('#cardCount').textContent=shown.length+' / '+cards.length+' cards';gallery.innerHTML=shown.length?shown.map(c=>`<button type="button" class="archive-card" data-card="${esc(c.id)}"><span class="archive-card-art">${safeCardImage(c.image_url)?`<img src="${esc(safeCardImage(c.image_url))}" alt="${esc(c.name)}" loading="lazy" referrerpolicy="no-referrer">`:''}<span class="card-art-fallback" aria-hidden="true">◇</span></span><span class="archive-card-caption"><small>${esc(c.domain||'UNFILED')} ${c.set?' / '+esc(c.set):''}</small><strong>${esc(c.name)}</strong><span>Inspect card ↗</span></span></button>`).join(''):`<div class="archive-empty"><img src="./assets/bamboo-scroll.svg" width="80" height="80" alt=""><h3>${cards.length?'No cards match this search.':'A collection worth studying.'}</h3><p>${cards.length?'Try another name or category.':'Add the cards you’re exploring this week. Their artwork will become your visual index.'}</p><button type="button" class="btn" id="cardEmptyAdd">${cards.length?'Clear filters':'Add your first card'}</button></div>`;
 gallery.querySelectorAll('img').forEach(img=>{img.onerror=()=>{img.hidden=true;};});gallery.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>inspect(cards.find(c=>c.id===b.dataset.card)));gallery.querySelector('#cardEmptyAdd')?.addEventListener('click',()=>{if(cards.length){query='';domain='';mountCardLibrary(root,api);}else edit();});}
 root.querySelector('#cardSearch').oninput=e=>{query=e.target.value;draw();};root.querySelector('#cardDomain').onchange=e=>{domain=e.target.value;draw();};root.querySelector('#cardAdd').onclick=()=>edit();draw();
 function inspect(card){api.modal(card.name,`<div class="card-inspector"><div class="card-inspector-art">${safeCardImage(card.image_url)?`<img src="${esc(safeCardImage(card.image_url))}" alt="${esc(card.name)}" referrerpolicy="no-referrer">`:'<span class="empty-symbol">◇</span>'}</div><div><span class="eyebrow">${esc(card.domain||'UNFILED')} · ${esc(card.set||'PERSONAL ARCHIVE')}</span><h3>${esc(card.name)}</h3><p class="card-study-note">${esc(card.text||'No study notes yet.')}</p><button type="button" class="btn primary" id="cardEdit">Edit card & notes</button></div></div>`);document.querySelector('#cardEdit').onclick=()=>edit(card);const img=document.querySelector('.card-inspector img');if(img)img.onerror=()=>{img.alt='Image unavailable — edit this card to update the image link.';};}
 function edit(card={}){api.modal(card.id?'Edit card':'Add a card',`<div class="card-editor"><label><span class="label-title">Card name</span><input id="cardName" maxlength="160" value="${esc(card.name||'')}"></label><div class="grid-2"><label><span class="label-title">Domain / category</span><input id="cardCategory" maxlength="80" value="${esc(card.domain||'')}" placeholder="e.g. Fury"></label><label><span class="label-title">Set</span><input id="cardSet" maxlength="80" value="${esc(card.set||'')}"></label></div><label><span class="label-title">Card image URL (optional)</span><input type="url" id="cardImage" value="${esc(card.image_url||'')}" placeholder="https://…"></label><label><span class="label-title">Interactions & questions to test</span><textarea id="cardNote" rows="4" maxlength="6000">${esc(card.text||'')}</textarea></label><p id="cardError" role="alert" class="cult-error"></p><button type="button" class="btn primary full" id="cardSave">Save card</button></div>`);document.querySelector('#cardSave').onclick=async()=>{const $=s=>document.querySelector(s),name=$('#cardName').value.trim(),url=$('#cardImage').value.trim();if(!name){$('#cardError').textContent='Give this card a name.';return;}if(url&&!safeCardImage(url)){$('#cardError').textContent='Use a valid HTTPS image URL.';return;}$('#cardSave').disabled=true;try{await put('notes',stampBase({...card,record_type:'library_card',name,image_url:safeCardImage(url),domain:$('#cardCategory').value.trim(),set:$('#cardSet').value.trim(),text:$('#cardNote').value.trim()}));window.dispatchEvent(new Event('riftmastery:localchange'));api.closeModal();await mountCardLibrary(root,api);api.toast('Card saved.');}catch{$('#cardSave').disabled=false;$('#cardError').textContent='Could not save. Your edits are still here.';}};}
}
