import {all,get,put,stampBase} from './db.js?v=0.12.0';
import {buildProgress,SKILLS,KINDS,REALMS,STATUSES,dayKey,validateTrial} from './cultivation-model.js?v=0.12.0';
const $=(s,r=document)=>r.querySelector(s),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let api;
export function configureCultivation(value){api=value;}
async function snapshot(){const names=['notes','weeklyChecklists','sessions','matches','reviewBlocks'];return Object.fromEntries(await Promise.all(names.map(async n=>[n,await all(n)])));}
async function save(row){await put('notes',row);window.dispatchEvent(new Event('riftmastery:localchange'));}
const crest=`<svg viewBox="0 0 100 100" fill="none" aria-hidden="true"><path d="M50 4 88 26v48L50 96 12 74V26Z"/><path d="M50 14 79 31v38L50 86 21 69V31Z"/><path d="M34 67V40l16-13 16 13v27M29 67h42M42 60V44l8-7 8 7v16M50 19v8M50 67v12"/><path d="m47 53 3-5 3 5-3 5Z"/></svg>`;
function bar(value,max,label){return `<div class="cult-bar" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${Math.min(max,value)}"><span style="width:${Math.min(100,max?value/max*100:0)}%"></span></div>`;}
function realmHTML(p,compact=false){return `<section class="cult-realm ${compact?'cult-compact':''}" aria-label="Cultivation progression"><div class="cult-crest">${crest}<span>${String(p.realmIndex+1).padStart(2,'0')}</span></div><div class="cult-realm-copy"><div class="eyebrow">YOUR CULTIVATION · ${p.xp.toLocaleString()} XP</div><h${compact?'3':'2'}>${p.realm[0]}</h${compact?'3':'2'}><p>${p.nextRealm?`${p.nextRealm[1]-p.xp} XP to ${p.nextRealm[0]}`:'The path continues. Keep refining your practice.'}</p>${bar(p.nextRealm?p.xp-p.realm[1]:1,p.nextRealm?p.nextRealm[1]-p.realm[1]:1,'Cultivation title progress')}<small>Practice titles track learning work. Skill is earned through evidence.</small></div><div class="cult-realm-side"><span class="cult-number">+${p.weeklyXP}</span><span class="eyebrow">XP THIS WEEK</span><button class="btn ${compact?'':'primary'}" data-cult="${compact?'progress':'log'}">${compact?'View your path':'Record a trial'}</button></div></section>`;}
function questHTML(p){return `<div class="cult-section-head"><div><span class="eyebrow">WEEK OF ${esc(p.week)}</span><h3>Four trials. One stronger player.</h3></div><span class="cult-badge">${p.quests.filter(q=>q.count>=q.target).length} / 4 complete</span></div><div class="cult-quests">${p.quests.map((q,i)=>`<article class="cult-quest ${q.count>=q.target?'is-complete':''}"><div class="cult-quest-top"><span class="cult-index">${q.count>=q.target?'✓':String(i+1).padStart(2,'0')}</span><span class="cult-badge">${q.xp} XP / record</span></div><h4>${q.label}</h4><p>${{study:'Pause a VOD before the reveal. Predict the line, then compare the reasoning.',drill:'Practice an awkward opening or compare two lines away from a live match.',research:'Test a preview or matchup question. Save evidence and a next test.',review:'Reconstruct a decision using what you knew then. Compare two credible lines.',discipline:'Finish the BO3 session size you committed to before playing.',transfer:'Return to an earlier lesson on a later day. See whether it holds up.'}[q.kind]}</p><div class="cult-quest-bottom"><span>${Math.min(q.count,q.target)} / ${q.target} records</span><button class="link-btn" data-cult="log" data-kind="${q.kind}">${q.count>=q.target?'Add evidence':'Begin trial'} <span aria-hidden="true">↗</span></button></div>${bar(q.count,q.target,q.label)}</article>`).join('')}</div>`;}
function skillsHTML(p){return `<div class="cult-section-head"><div><span class="eyebrow">EVIDENCE BEFORE PROMOTION</span><h3>Your skill path</h3></div><span class="small muted">Self-assessed · never raised by XP</span></div><div class="cult-skills">${p.skills.map(s=>`<article class="cult-skill ${s.id===p.focus?'is-focus':''}"><div class="cult-skill-title"><h4>${esc(s.name)}</h4><span class="cult-badge">${s.status}</span></div><p>${esc(s.cue)}</p><div class="cult-skill-steps" aria-label="${esc(s.name)}: ${s.status}">${STATUSES.map((x,i)=>`<span class="${i<=STATUSES.indexOf(s.status)?'earned':''}" title="${x}"></span>`).join('')}</div><div class="small muted">${s.days} evidence days · ${s.transfers} successful retests</div><div class="cult-skill-actions"><button class="link-btn" data-cult="skill" data-skill="${s.id}">Inspect evidence</button><button class="link-btn" data-cult="focus" data-skill="${s.id}" aria-pressed="${s.id===p.focus}">${s.id===p.focus?'Current focus':'Set focus'}</button></div></article>`).join('')}</div>`;}
function ledger(p){return `<details class="cult-ledger"><summary>Evidence ledger <span>${p.events.length} records</span></summary><p class="small muted">Existing completed reviews, research, supported X drafts, and precommitted BO3 sessions count automatically. Don’t log them twice. Each category has a weekly XP cap; additional evidence still counts for skills.</p>${p.events.length?`<div class="cult-ledger-list">${p.events.slice().reverse().slice(0,30).map(e=>`<div class="cult-ledger-row"><div><strong>${esc(e.title)}</strong><small>${e.day} · ${KINDS[e.kind].verb}${e.outcome?' · '+esc(e.outcome.replaceAll('_',' ')):''}</small></div><span>${e.xp?'+'+e.xp+' XP':'Evidence only'}</span>${e.kind&&e.id?`<button class="link-btn" data-cult="record" data-id="${esc(e.id)}">Inspect</button>`:''}</div>`).join('')}</div>`:'<p class="muted">Your first trial begins this record.</p>'}<div class="cult-rule-grid">${Object.values(KINDS).map(k=>`<span>${k.verb}<b>${k.xp} XP × ${k.cap}/week</b></span>`).join('')}<span>Weekly checklist<b>40 XP / week</b></span><span>Breakthrough review<b>60 XP / week</b></span></div><p class="small muted">XP recalculates from saved records, so editing or correcting a record cannot award it twice. Removing its evidence removes its XP. Wins, losses, time spent, and social metrics award no XP.</p></details>`;}
export async function mountCultivation(root,mode='full'){
 if(!root)return;const p=buildProgress(await snapshot());
 if(mode==='home')root.innerHTML=realmHTML(p,true)+`<div class="cult-home-next"><span><b>Next step</b> · ${esc(p.quests.find(q=>q.count<q.target)?.label||'Review this week’s breakthrough')}</span><button class="link-btn" data-cult="${p.quests.some(q=>q.count<q.target)?'log':'checkpoint'}" data-kind="${p.quests.find(q=>q.count<q.target)?.kind||'drill'}">${p.quests.some(q=>q.count<q.target)?'Open trial':'Review week'} ↗</button></div>`;
 else if(mode==='skills')root.innerHTML=skillsHTML(p);
 else root.innerHTML=`${realmHTML(p)}<div class="cult-focus-line"><span>ACTIVE SKILL</span><strong>${esc(SKILLS.find(s=>s[0]===p.focus)?.[1]||SKILLS[0][1])}</strong><a href="#cultSkillPath">Choose your focus ↓</a></div>${questHTML(p)}<section class="cult-breakthrough"><div><span class="eyebrow">WEEKLY BREAKTHROUGH · 60 XP</span><h3>${p.checkpointDone?'Lesson carried forward.':'Prove the lesson travels.'}</h3><p>Complete three kinds of learning work, including a later-day retest. Then name what changed and your next drill.</p><span class="small muted">${p.checkpointDone?'Review saved. Edit it any time.':p.checkpointReady?'Your evidence is ready for review.':`${new Set(p.current.map(e=>e.kind)).size} / 3 kinds · ${p.current.some(e=>e.kind==='transfer')?'retest recorded':'retest still needed'}`}</span></div><button class="btn ${p.checkpointReady?'primary':''}" data-cult="checkpoint" ${!p.checkpointReady?'disabled':''}>${p.checkpointDone?'Revisit review':'Review breakthrough'}</button></section><div id="cultSkillPath">${skillsHTML(p)}</div><div class="cult-section-head"><div><span class="eyebrow">MILESTONES ALONG THE WAY</span><h3>Your seals</h3></div></div><div class="cult-seals">${p.seals.map(([name,earned,detail])=>`<div class="cult-seal ${earned?'earned':''}"><span aria-hidden="true">${earned?'✧':'◇'}</span><strong>${name}</strong><small>${detail}</small><b>${earned?'Earned':'Not yet earned'}</b></div>`).join('')}</div>${ledger(p)}<details class="cult-ledger"><summary>The cultivation path</summary><div class="cult-realm-list">${REALMS.map(([name,xp],i)=>`<div class="${p.xp>=xp?'earned':''}"><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong><small>${xp.toLocaleString()} XP</small></div>`).join('')}</div><p class="small muted">A personal practice journey, not a competitive rating. No daily streak penalty. Rest days and losses do not reset your progress.</p></details><button class="link-btn small" data-cult="archive">Removed trial records</button>`;
 bind(root,p);
}
function bind(root,p){root.querySelectorAll('[data-cult]').forEach(b=>b.onclick=async()=>{
 const action=b.dataset.cult;
 if(action==='archive'){const removed=(await all('notes',{includeDeleted:true})).filter(n=>n.deleted_at&&n.record_type==='cultivation_trial');api.showModal('Removed trial records',removed.length?removed.map(n=>`<div class="cult-ledger-row"><div><strong>${esc(n.lesson)}</strong><small>${esc(n.day)}</small></div><button type="button" class="btn small" data-restore="${esc(n.id)}">Restore</button></div>`).join(''):'<p>No removed trials.</p>');document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{b.disabled=true;const row=removed.find(n=>n.id===b.dataset.restore);await save({...row,deleted_at:null});api.closeModal();await api.refresh();api.toast('Trial restored.');});return;}
 if(action==='progress')return api.navigate('stats');
 if(action==='log')return openTrial(b.dataset.kind||'drill');
 if(action==='checkpoint')return openCheckpoint();
 if(action==='skill')return openSkill(b.dataset.skill);
 if(action==='record'){const n=await get('notes',b.dataset.id);if(n?.record_type==='cultivation_trial')return openTrial(n.kind,n);if(n){api.showModal('Saved evidence',`<p class="small muted">${esc(n.record_type?.replaceAll('_',' ')||'Learning record')}</p><h3>${esc(n.question||n.hook||'Learning record')}</h3><p>${esc(n.takeaway||n.finding||n.claim||n.text||'')}</p><button type="button" class="btn" id="cultSource">Open source workspace</button>`);$('#cultSource').onclick=async()=>{api.closeModal();await api.navigate(n.record_type==='x_post'?'studio':'lab',n.record_type==='position_review'?'positions':'research');};return;}return api.navigate('lab','blocks');}
 if(action==='focus'){await save(stampBase({id:'cultivation-focus',record_type:'cultivation_focus',skill:b.dataset.skill,text:'Active cultivation skill'}));await mountCultivation(root,root.id==='cultHome'?'home':root.id==='cultSkills'?'skills':'full');}
 });}
async function finish(before,message){api.closeModal();const after=buildProgress(await snapshot()),delta=after.xp-before.xp;await api.refresh();api.toast(after.realmIndex>before.realmIndex?`${after.realm[0]} reached · ${after.xp} XP`:`${message}${delta>0?' · +'+delta+' XP':''}`);}
async function openTrial(kind='drill',existing=null){
 const data=await snapshot(),p=buildProgress(data),n=existing||{},skill=n.skill||p.focus;
 const sources=data.notes.filter(x=>['cultivation_trial','position_review','preview_research'].includes(x.record_type)&&x.id!==n.id).sort((a,b)=>String(b.timestamp||b.created_at).localeCompare(String(a.timestamp||a.created_at)));
 api.showModal(existing?'Revisit your trial':'Record a completed trial',`<div class="cult-editor-intro"><span class="eyebrow">AFTER PRACTICE · ABOUT A MINUTE</span><p>Record one useful observation and what you will test next. Honest uncertainty counts. Use the existing review or research record if you already saved it.</p></div><label><span class="label-title">Trial</span><select id="cultKind">${Object.entries(KINDS).map(([id,k])=>`<option value="${id}" ${id===kind?'selected':''}>${k.label} · ${k.xp} XP</option>`).join('')}</select></label><label><span class="label-title">Skill</span><select id="cultSkill">${SKILLS.map(([id,name])=>`<option value="${id}" ${id===skill?'selected':''}>${name}</option>`).join('')}</select></label><label><span class="label-title">Practice date</span><input type="date" id="cultDay" value="${esc(n.day||dayKey())}" max="${dayKey()}"></label><label><span class="label-title">Practice setting</span><select id="cultContext">${[['practice','Games / practice'],['vod','VOD study'],['drill','Off-table drill'],['event','Tournament']].map(([id,name])=>`<option value="${id}" ${n.context===id?'selected':''}>${name}</option>`).join('')}</select></label><div id="cultTransfer" class="editor-span"><label><span class="label-title">Earlier lesson being retested</span><select id="cultSourceId"><option value="">Choose a saved lesson</option>${sources.map(x=>`<option value="${esc(x.id)}" ${n.source_id===x.id?'selected':''}>${esc((x.day||dayKey(x.timestamp||x.created_at))+' · '+(x.lesson||x.question||x.text||'Lesson').slice(0,90))}</option>`).join('')}</select></label><label><span class="label-title">Did it hold up?</span><select id="cultOutcome"><option value="uncertain">Still uncertain</option><option value="observed">Yes, I observed it working</option><option value="needs_work">No, it needs more work</option></select></label><p class="small muted">Use a later day than the original lesson. Every honest retest earns the same XP.</p></div><label><span class="label-title" id="cultLessonLabel">What did you observe?</span><textarea id="cultLesson" rows="3" maxlength="1600" placeholder="Name the position, prediction, or decision and what you learned.">${esc(n.lesson||'')}</textarea></label><label><span class="label-title">What will you test or do differently next?</span><textarea id="cultNext" rows="2" maxlength="1000" placeholder="One specific next rep, not a general goal.">${esc(n.next_test||'')}</textarea></label><p id="cultError" class="cult-error editor-span" role="alert"></p><div class="btn-row">${existing?'<button type="button" class="btn ghost" id="cultVoid">Remove this record</button>':''}<button type="button" class="btn primary" id="cultSave">Save learning evidence</button></div>`);
 $('#cultOutcome').value=n.outcome||'uncertain';const toggle=()=>{$('#cultTransfer').hidden=$('#cultKind').value!=='transfer';const k=$('#cultKind').value;$('#cultLessonLabel').textContent=k==='study'?'What did you predict, and what did comparison teach you?':k==='review'?'What were the two lines, and what did the comparison show?':k==='discipline'?'What was your precommitted limit, and did you honor it?':'What did you observe?';};$('#cultKind').onchange=toggle;toggle();
 $('#cultSourceId').onchange=()=>{const source=sources.find(s=>s.id===$('#cultSourceId').value);if(source?.skill)$('#cultSkill').value=source.skill;};
 $('#cultSave').onclick=async()=>{const button=$('#cultSave');if(button.disabled)return;const row={...n,record_type:'cultivation_trial',kind:$('#cultKind').value,skill:$('#cultSkill').value,day:$('#cultDay').value,context:$('#cultContext').value,lesson:$('#cultLesson').value.trim(),next_test:$('#cultNext').value.trim(),source_id:$('#cultSourceId').value||null,outcome:$('#cultOutcome').value};const error=validateTrial(row,data.notes);if(error){$('#cultError').textContent=error;return;}button.disabled=true;try{const record=existing?row:stampBase(row);record.timestamp=record.timestamp||new Date().toISOString();record.text=record.lesson;await save(record);await finish(p,'Learning evidence saved');}catch(e){button.disabled=false;$('#cultError').textContent='Could not save. Your draft is still here; try again.';}};
 if(existing)$('#cultVoid').onclick=async()=>{if($('#cultVoid').dataset.confirm!=='yes'){$('#cultVoid').dataset.confirm='yes';$('#cultVoid').textContent='Confirm removal (can undo)';return;}await save({...existing,deleted_at:new Date().toISOString()});await finish(p,'Record removed');api.showModal('Record removed',`<p>You can restore this record now.</p><button type="button" class="btn primary" id="cultUndo">Undo removal</button>`);$('#cultUndo').onclick=async()=>{await save({...existing,deleted_at:null});api.closeModal();await api.refresh();api.toast('Record restored.');};};
}
async function openCheckpoint(){const data=await snapshot(),p=buildProgress(data);if(!p.checkpointReady){api.toast('Complete three kinds of trials, including a later-day retest.');return;}const old=data.notes.find(n=>n.id==='cultivation-checkpoint:'+p.week);api.showModal('Your weekly breakthrough',`<p class="small muted">Judge the process, not the score. A failed retest can reveal the next useful drill.</p><label><span class="label-title">What changed in your decisions this week?</span><textarea id="cultLesson" rows="3">${esc(old?.lesson||'')}</textarea></label><label><span class="label-title">One drill for the next week</span><textarea id="cultNext" rows="2">${esc(old?.next_test||'')}</textarea></label><p id="cultError" role="alert" class="cult-error"></p><button type="button" class="btn primary full" id="cultSave">Seal this week · ${p.checkpointDone?'already earned':'60 XP'}</button>`);$('#cultSave').onclick=async()=>{const lesson=$('#cultLesson').value.trim(),next_test=$('#cultNext').value.trim();if(lesson.length<8||next_test.length<8){$('#cultError').textContent='Add a specific change and next drill.';return;}$('#cultSave').disabled=true;try{await save(stampBase({...old,id:'cultivation-checkpoint:'+p.week,record_type:'cultivation_checkpoint',week:p.week,lesson,next_test,text:lesson}));await finish(p,'Weekly breakthrough saved');}catch{$('#cultSave').disabled=false;$('#cultError').textContent='Could not save. Try again.';}};}
async function openSkill(id){const p=buildProgress(await snapshot()),s=p.skills.find(x=>x.id===id);if(!s)return;
 api.showModal(s.name,`<p class="muted">${esc(s.cue)}</p><div class="cult-status-guide">${[['Developing','Execution is inconsistent or fragile.'],['Functional','Works in familiar positions. Minimum: 2 evidence days.'],['Reliable','Holds up across varied positions. Minimum: 4 days, 2 settings, 2 successful retests.'],['Weapon','Creates an edge you can explain. Minimum: 6 days, 2 settings, 3 successful retests, 1 explanation.']].map(([name,cue])=>`<p><strong>${name}</strong><span>${cue}</span></p>`).join('')}</div><p class="small muted">These are minimum evidence gates, not proof of mastery. Promote only when your decisions support the description.</p><label><span class="label-title">Your assessment</span><select id="cultStatus">${STATUSES.map((x,i)=>`<option value="${x}" ${s.status===x?'selected':''} ${!s.eligible[i]&&s.status!==x?'disabled':''}>${x}${!s.eligible[i]?' · more evidence needed':''}</option>`).join('')}</select></label><label><span class="label-title">Evidence for this assessment / remaining weakness</span><textarea id="cultReason" rows="3">${esc(s.assessment?.reason||'')}</textarea></label><details class="cult-ledger"><summary>${s.evidence.length} supporting records · ${s.days} days</summary>${s.evidence.slice(-12).reverse().map(e=>`<p class="small"><b>${e.day} · ${KINDS[e.kind].verb}</b><br>${esc(e.title)}</p>`).join('')||'<p>No evidence yet. Start with one focused trial.</p>'}</details><p id="cultError" role="alert" class="cult-error"></p><button type="button" class="btn primary full" id="cultSave">Save assessment</button>`);
 $('#cultSave').onclick=async()=>{const status=$('#cultStatus').value,reason=$('#cultReason').value.trim();if(!s.eligible[STATUSES.indexOf(status)]&&status!==s.status){$('#cultError').textContent='More evidence is needed for this status.';return;}if(reason.length<8){$('#cultError').textContent='Explain the evidence or remaining weakness.';return;}$('#cultSave').disabled=true;try{await save(stampBase({id:'cultivation-assessment:'+id,record_type:'cultivation_assessment',skill:id,status,reason,text:reason}));await finish(p,'Skill assessment saved');}catch{$('#cultSave').disabled=false;$('#cultError').textContent='Could not save. Try again.';}};
}
