import {SKILLS,dayKey,buildProgress} from './cultivation-model.js?v=0.13.0';
export const PRACTICES={
 'open-board':{title:'Compare before you commit.',kind:'drill',context:'drill',steps:['Choose one unfamiliar board from a replay or a practice setup. Stop before the next action.','Say who benefits from waiting. Name two credible lines and the opponent response that punishes each.','Choose the better next-turn position. Explain why, using only information available at the time.'],next:'Repeat the two-line comparison in a different open-board position.'},
 ranges:{title:'Read what the pass tells you.',kind:'study',context:'vod',steps:['Pause a replay before a meaningful opponent action or pass. Name three plausible answers.','Watch that action. Say which answers become more or less likely, and why.','Compare two possible lines against the updated range before revealing what happens.'],next:'Track an action and a non-action in another position before choosing a line.'},
 openings:{title:'Find a plan when Plan A is missing.',kind:'drill',context:'drill',steps:['Take a sample opening hand and remove access to the engine or ideal early piece.','Name the function that is missing. Build a functional line and a salvage line.','Say when you would abandon the original plan. Repeat with a different missing piece.'],next:'Practice a second missing-piece opening and explain when the role changes.'},
 sequencing:{title:'Build the end of the turn first.',kind:'drill',context:'drill',steps:['Choose a turn with at least two meaningful actions. Picture the board you want when you pass.','Work backward. Compare two action orders and the resources or information each spends.','Check what options each order leaves for the opponent’s response. Explain the safer sequence.'],next:'Compare two action orders in a new turn while preserving one response.'},
 geometry:{title:'Decide what the point really costs.',kind:'study',context:'vod',steps:['Pause a replay before a battlefield commitment or scoring opportunity.','Compare taking the point now with holding resources. Count bodies, cards, runes, and next-turn options.','Choose a line before the reveal. Separate whether it was reasonable from whether it won.'],next:'Compare forcing and waiting in another scoring window.'},
 matchups:{title:'Give the matchup a second plan.',kind:'drill',context:'drill',steps:['Choose one matchup you expect to play. State your role and primary route to winning.','Assume the centerpiece is answered. Name an alternate route and the resource it needs.','Compare two opening hands or sideboard choices against that plan. Explain what changes your role.'],next:'Test the alternate plan in a second opening or post-board position.'},
 discipline:{title:'Close the session without chasing it.',kind:'review',context:'practice',steps:['Review a completed session against the limit you set before playing.','Name one decision you handled well and one recurring leak. Keep the record separate from the diagnosis.','Choose one drill for the next session. If you exceeded your limit, name the trigger without excusing it.'],next:'Precommit the next session size and stop at the agreed limit.'},
 theory:{title:'Turn one question into a test.',kind:'research',context:'drill',steps:['Choose one card, deck, or matchup question. State your working hypothesis before testing.','Run a small comparison, inspect a replay, or verify the relevant card text. Record what actually supports or challenges it.','Keep the conclusion narrow. Say what remains uncertain and what evidence would change your mind.'],next:'Retest the hypothesis with another position or source that could disprove it.'}
};
export function practiceState(data,now=new Date()){
 const p=buildProgress(data,now),notes=(data.notes||[]).filter(n=>!n.deleted_at),today=dayKey(now);
 const active=notes.filter(n=>n.record_type==='cultivation_practice'&&n.status==='active'&&!notes.some(e=>e.record_type==='cultivation_trial'&&e.practice_id===n.id)).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))[0];
 const skill=SKILLS.some(s=>s[0]===p.focus)?p.focus:'open-board',base=PRACTICES[skill];
 const learned=notes.filter(n=>n.record_type==='cultivation_trial'&&n.skill===skill&&n.lesson?.trim().length>=8).sort((a,b)=>String(b.day).localeCompare(String(a.day))||String(b.created_at).localeCompare(String(a.created_at)));
 const prior=learned.find(n=>n.day<today&&!notes.some(t=>t.record_type==='cultivation_trial'&&t.kind==='transfer'&&t.source_id===n.id&&t.day===today));
 const todayEvidence=p.events.filter(e=>e.day===today&&e.skill===skill),latest=todayEvidence.at(-1);
 const recommendation=prior?{...base,title:'Carry the lesson into a new position.',kind:'transfer',source_id:prior.id,source_lesson:prior.lesson,steps:[`Return to this lesson: “${prior.lesson}”`,'Choose a different position or practice game where the same idea matters. Apply it before you know the result.','Afterward, say whether the idea held up, broke down, or still needs evidence.'],next:prior.next_test||base.next}:base;
 return {p,skill,active,latest,doneToday:todayEvidence.length>0,recommendation:{...recommendation,skill,minutes:10},today};
}
export function suggestedWeeklyItem(plan,week){
 const pending=(week?.items||[]).filter(i=>!i.done&&!i.optional);
 const ids=plan.kind==='study'?['vod-1','vod-2']:plan.kind==='research'?['preview-test','prerift-notes']:plan.skill==='open-board'&&plan.kind==='drill'?['board-drill']:[];
 return pending.find(i=>ids.includes(i.id))||null;
}
