import {all,get,put,stampBase} from './db.js?v=0.13.0';
import {SKILLS,KINDS,buildProgress,dayKey,validateTrial,weekKey} from './cultivation-model.js?v=0.13.0';
import {practiceState,PRACTICES,suggestedWeeklyItem} from './practice-model.js?v=0.13.0';
const $=(s,r=document)=>r.querySelector(s),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let api;
export function configurePractice(value){api=value;}
async function data(){const names=['notes','weeklyChecklists','sessions','matches','reviewBlocks'];return Object.fromEntries(await Promise.all(names.map(async n=>[n,await all(n)])));}
async function save(store,row){await put(store,row);window.dispatchEvent(new Event('riftmastery:localchange'));}
export async function mountHomePractice(root){
 if(!root)return;const state=practiceState(await data()),{p,active,latest,doneToday,recommendation,skill}=state;
 const title=active?active.title:doneToday?'Today’s work is banked.':recommendation.title;
 root.innerHTML=`<section class="courtyard-scene" aria-label="Your daily practice"><img class="courtyard-painting" src="./assets/fang-yuan-courtyard-v2.webp" width="1672" height="941" alt="Fang Yuan sleeping in a mountain courtyard at dusk" fetchpriority="high"><div class="courtyard-veil" aria-hidden="true"></div><div class="scene-topline"><span>01 / YOUR INNER COURTYARD</span><span>RIFTBOUND · PERSONAL PRACTICE</span></div><div class="courtyard-title"><h2>The Inner<br><em>Courtyard.</em></h2><p>Still the mind.<br>Sharpen the next decision.</p></div><span class="scene-inscription">REST IS PART OF MASTERY</span><div class="practice-dock"><div class="dock-focus"><span class="eyebrow">${active?'PRACTICE IN PROGRESS':doneToday?'EVIDENCE SAVED':'YOUR NEXT PRACTICE'} · ${active?.minutes||'10–20'} MIN</span><h3>${esc(title)}</h3><div class="dock-skill">${esc(SKILLS.find(s=>s[0]===(active?.skill||skill))?.[1]||'Practice')}<button type="button" class="link-btn" id="dailyFocus">Change focus</button></div></div><div class="dock-action"><button type="button" class="btn primary" id="dailyBegin">${active?'Resume practice':doneToday?'See what changed':'Begin practice'} <span aria-hidden="true">↗</span></button><button type="button" class="link-btn" id="dailyDebrief">${doneToday&&!active?'Another practice':'I already practiced'}</button></div></div></section><div class="courtyard-understory"><p>${active?'Your practice is saved. Pick up where you left off.':doneToday?esc(latest.title):esc(recommendation.steps[0])}</p><div class="daily-path" aria-label="Your practice loop"><span class="${active||doneToday?'complete':'current'}"><b>01</b> Practice</span><i aria-hidden="true"></i><span class="${doneToday?'complete':active?'current':''}"><b>02</b> Observe</span><i aria-hidden="true"></i><span><b>03</b> Test again</span></div></div>`;
 $('#dailyBegin',root).onclick=()=>active?openPractice(active):doneToday?api.navigate('stats'):choosePractice();
 $('#dailyDebrief',root).onclick=()=>doneToday&&!active?choosePractice():quickDebrief(active||{...recommendation,id:null},true);
 $('#dailyFocus',root).onclick=chooseFocus;
}
async function chooseFocus(){const {p}=practiceState(await data());api.showModal('One skill to carry forward',`<p class="muted">Choose the weakness you want your next practice to address. Your current practice, if any, keeps its original focus.</p><div class="practice-focus-options">${SKILLS.map(([id,name,cue])=>`<button type="button" class="practice-focus-option ${p.focus===id?'selected':''}" data-practice-focus="${id}"><strong>${esc(name)}</strong><span>${esc(cue)}</span></button>`).join('')}</div><p id="practiceError" role="alert" class="cult-error"></p>`);document.querySelectorAll('[data-practice-focus]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await save('notes',stampBase({id:'cultivation-focus',record_type:'cultivation_focus',skill:b.dataset.practiceFocus,text:'Active cultivation skill'}));api.closeModal();await api.refresh();}catch{b.disabled=false;$('#practiceError').textContent='Could not save the focus. Try again.';}});}
async function choosePractice(){const {recommendation:r,skill}=practiceState(await data());api.showModal('Make room for one useful rep',`<p class="small muted">${esc(SKILLS.find(s=>s[0]===skill)?.[1])}</p><h3 class="practice-dialog-title">${esc(r.title)}</h3><p class="muted">${esc(r.steps[0])}</p><div class="practice-duration" role="group" aria-label="Practice length"><button type="button" aria-pressed="true" class="selected" data-minutes="10"><strong>10 min</strong><span>One position</span></button><button type="button" aria-pressed="false" data-minutes="20"><strong>20 min</strong><span>Compare two positions</span></button></div>${r.kind==='transfer'?'<p class="small muted">This returns to a lesson from an earlier day.</p>':''}<p class="small muted">No timer to race. Nothing to write while you play.</p><p id="practiceError" role="alert" class="cult-error"></p><button type="button" class="btn primary full" id="practiceStart">Start this practice</button>`);
 let minutes=10;document.querySelectorAll('[data-minutes]').forEach(b=>b.onclick=()=>{minutes=Number(b.dataset.minutes);document.querySelectorAll('[data-minutes]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});});
 $('#practiceStart').onclick=async()=>{const b=$('#practiceStart');if(b.disabled)return;b.disabled=true;try{const plan=stampBase({...r,minutes,record_type:'cultivation_practice',status:'active',text:r.title});await save('notes',plan);await api.refresh();await openPractice(plan);}catch{b.disabled=false;$('#practiceError').textContent='Could not start practice. Try again.';}};
}
async function openPractice(plan){api.showModal('Your practice',`<div class="practice-session-head"><span class="eyebrow">${plan.minutes} MINUTES · ${esc(SKILLS.find(s=>s[0]===plan.skill)?.[1]||'Focused practice')}</span><h3 class="practice-dialog-title">${esc(plan.title)}</h3></div><ol class="practice-steps">${plan.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${plan.minutes===20?'<p class="small muted">Repeat with a second position. Look for what stays true and what changes.</p>':''}<div class="practice-quiet"><strong>Stay with the game.</strong><span>Leave this screen when you need to. Your practice is saved; debrief afterward.</span></div><div class="btn-row"><button type="button" class="btn primary" id="practiceDone">Ready to debrief</button><button type="button" class="btn ghost" id="practicePause">Come back later</button></div><button type="button" class="link-btn small" id="practiceReplace">Set this aside</button><p id="practiceError" role="alert" class="cult-error"></p>`);$('#practiceDone').onclick=()=>quickDebrief(plan);$('#practicePause').onclick=()=>api.closeModal();$('#practiceReplace').onclick=async()=>{const b=$('#practiceReplace');b.disabled=true;try{await save('notes',{...plan,status:'parked'});api.closeModal();await api.refresh();}catch{b.disabled=false;$('#practiceError').textContent='Could not set practice aside. Try again.';}};}
async function quickDebrief(plan,already=false){const d=await data(),before=buildProgress(d),week=d.weeklyChecklists.find(w=>w.week_start===weekKey()),item=suggestedWeeklyItem(plan,week),isTransfer=plan.kind==='transfer';let outcome='';
 const evidenceId=plan.id?'practice-evidence:'+plan.id:stampBase().id;
 api.showModal('What changed in your thinking?',`<div class="practice-debrief-head"><span class="eyebrow">AFTER PRACTICE · ONE OBSERVATION</span><p>${isTransfer?`Earlier lesson: ${esc(plan.source_lesson||'Retest the saved lesson.')}`:'A clearer decision, a failed idea, or an honest uncertainty all count.'}</p></div><div class="practice-outcomes" role="group" aria-label="Practice outcome">${[['observed','Clearer now'],['needs_work','Needs work'],['uncertain','Still unsure']].map(([id,label])=>`<button type="button" aria-pressed="false" data-outcome="${id}">${label}</button>`).join('')}</div><label><span class="label-title">${isTransfer?'What happened when you tested the lesson again?':'What did you notice?'} </span><textarea id="practiceObservation" rows="3" maxlength="1600" placeholder="One concrete decision or observation. A sentence is enough."></textarea></label><details class="practice-details"><summary>${already?'Practice details · check these match what you did':'Adjust practice details or next step'}</summary><label><span class="label-title">Practice type</span><select id="practiceKind">${Object.entries(KINDS).filter(([id])=>isTransfer?id==='transfer':id!=='transfer').map(([id,k])=>`<option value="${id}" ${id===plan.kind?'selected':''}>${k.label}</option>`).join('')}</select></label><label><span class="label-title">Setting</span><select id="practiceContext">${[['drill','Off-table drill'],['vod','VOD study'],['practice','Games / practice'],['event','Tournament']].map(([id,label])=>`<option value="${id}" ${id===plan.context?'selected':''}>${label}</option>`).join('')}</select></label><label><span class="label-title">Next step</span><textarea id="practiceNext" rows="2" maxlength="1000">${esc(plan.next||PRACTICES[plan.skill].next)}</textarea></label></details>${item?`<label class="practice-weekly-credit"><input type="checkbox" id="practiceWeekly" checked><span>Also complete: <strong>${esc(item.title)}</strong></span></label>`:''}<p id="practiceError" class="cult-error" role="alert"></p><button type="button" class="btn primary full" id="practiceSave">Save & finish</button>`);
 document.querySelectorAll('[data-outcome]').forEach(b=>b.onclick=()=>{outcome=b.dataset.outcome;document.querySelectorAll('[data-outcome]').forEach(x=>{x.setAttribute('aria-pressed',String(x===b));x.classList.toggle('selected',x===b);});});
 // A different practice type should never silently complete the suggested checklist item.
 $('#practiceKind').onchange=()=>{if($('#practiceWeekly'))$('#practiceWeekly').checked=false;};
 $('#practiceSave').onclick=async()=>{const button=$('#practiceSave');if(button.disabled)return;const row=stampBase({id:evidenceId,practice_id:plan.id||null,record_type:'cultivation_trial',kind:$('#practiceKind').value,skill:plan.skill,day:dayKey(),context:$('#practiceContext').value,lesson:$('#practiceObservation').value.trim(),next_test:$('#practiceNext').value.trim(),source_id:plan.source_id||null,outcome,timestamp:new Date().toISOString()});row.text=row.lesson;
 const error=outcome?validateTrial(row,d.notes):'Choose how the practice went.';if(error){$('#practiceError').textContent=error;return;}button.disabled=true;
 try{const existing=await get('notes',evidenceId);await save('notes',existing?{...existing,...row,created_at:existing.created_at}:row);
 if(item&&$('#practiceWeekly')?.checked){const fresh=await get('weeklyChecklists',week.id),target=fresh?.items?.find(i=>i.id===item.id);if(target){target.done=true;target.evidence_ids=[...new Set([...(target.evidence_ids||[]),evidenceId])];await save('weeklyChecklists',fresh);}}
 if(plan.id)await save('notes',{...plan,status:'completed',completed_at:new Date().toISOString()});
 api.closeModal();await api.refresh();const after=buildProgress(await data()),delta=after.xp-before.xp;
 api.showModal('A lesson worth carrying forward',`<div class="practice-receipt"><span class="practice-receipt-seal" aria-hidden="true">✧</span><span class="eyebrow">${delta>0?'+'+delta+' XP · ':' '}EVIDENCE SAVED${after.realmIndex>before.realmIndex?' · '+after.realm[0].toUpperCase()+' REACHED':''}</span><h3>${outcome==='observed'?'A clearer read.':outcome==='needs_work'?'A useful weakness found.':'A better question to test.'}</h3><blockquote>${esc(row.lesson)}</blockquote><div class="practice-next"><span>NEXT TIME</span><p>${esc(row.next_test)}</p></div><p class="small muted">Your next practice can return to this lesson on a later day. You can stop here.</p><button type="button" class="btn primary full" id="practiceReturn">Back to my courtyard</button><button type="button" class="link-btn" id="practiceEvidence">See my evidence</button></div>`);$('#practiceReturn').onclick=async()=>{api.closeModal();await api.navigate('home');};$('#practiceEvidence').onclick=async()=>{api.closeModal();await api.navigate('stats');};
 }catch{button.disabled=false;$('#practiceError').textContent='Could not finish saving. Your observation is still here. Retry safely; this practice can only earn XP once.';}};
}
