import assert from 'node:assert/strict';
import {buildProgress,validateTrial,weekKey} from '../cultivation-model.js';
const now=new Date('2026-09-30T12:00:00');
const trial=(id,kind='drill',day='2026-09-28',extra={})=>({id,record_type:'cultivation_trial',kind,day,skill:'open-board',context:'drill',lesson:'Compare two lines before committing.',next_test:'Test the same choice with one fewer resource.',...extra});
let a=trial('a'),b=trial('b','study');
assert.equal(buildProgress({},now).xp,0);
assert.equal(buildProgress({notes:[a]},now).xp,30);
assert.equal(buildProgress({notes:[a,a]},now).xp,30,'duplicate imports must not duplicate XP');
assert.equal(buildProgress({notes:[a,{...a,lesson:'Changed the supporting explanation.'}]},now).xp,30,'edits do not increment XP');
assert.equal(buildProgress({notes:[a,trial('c'),trial('d')]},now).xp,60,'weekly category cap');
assert.equal(buildProgress({notes:[{...a,deleted_at:'yes'}]},now).xp,0);
assert.equal(buildProgress({notes:[trial('future','drill','2026-10-01')]},now).xp,0);
assert.match(validateTrial({...a,day:'2026-02-30'},[], '2026-09-30'),/valid date/);
assert.equal(weekKey('2026-09-27'),'2026-09-21');assert.equal(weekKey('2026-09-28'),'2026-09-28');
const transfer=trial('t','transfer','2026-09-29',{source_id:'a',outcome:'uncertain'});
assert.equal(validateTrial(transfer,[a,transfer],'2026-09-30'),'');
assert.match(validateTrial({...transfer,day:a.day},[a],'2026-09-30'),/later day/);
assert.equal(buildProgress({notes:[a,transfer]},now).xp,80);
assert.equal(buildProgress({notes:[a,{...transfer,outcome:'observed'}]},now).xp,80,'success does not earn extra XP');
assert.equal(buildProgress({notes:[transfer]},now).xp,0,'missing source removes transfer credit');
const checkpoint={id:'cp',record_type:'cultivation_checkpoint',week:'2026-09-28',lesson:'The retest exposed a sequencing weakness.',next_test:'Practice holding interaction for the later window.'};
assert.equal(buildProgress({notes:[a,b,transfer,checkpoint]},now).xp,170);
assert.equal(buildProgress({notes:[a,transfer,checkpoint]},now).xp,80,'requires 3 different kinds');
assert.equal(buildProgress({notes:[a,b,transfer,checkpoint,{...checkpoint,id:'cp2'}]},now).xp,170,'one checkpoint per week');
assert.equal(buildProgress({notes:[a],matches:[{id:'win',result:'me',ended_at:'2026-09-28'}]},now).xp,30);
assert.equal(buildProgress({notes:[a],matches:[{id:'loss',result:'opponent',ended_at:'2026-09-28'}]},now).xp,30);
assert.equal(buildProgress({notes:[a,transfer]},now).skills[0].eligible[1],true);
assert.equal(buildProgress({notes:[a,transfer]},now).skills[0].status,'Developing','no auto skill promotion');
const session={id:'s',status:'completed',planned_bo3_count:2,ended_at:'2026-09-29T12:00:00'};
const matches=[1,2].map(i=>({id:'m'+i,session_id:'s',format:'BO3',ended_at:'2026-09-29T12:00:00'}));
assert.equal(buildProgress({sessions:[session],matches},now).xp,20);
assert.equal(buildProgress({sessions:[session],matches:[...matches,{...matches[0],id:'m3'}]},now).xp,0,'no reward for redemption games');
const plan={id:'w',week_start:'2026-09-28',items:[{done:true},{done:false,optional:true}]};
assert.equal(buildProgress({weeklyChecklists:[plan]},now).xp,40);
assert.equal(buildProgress({weeklyChecklists:[{...plan,items:[]}]},now).xp,0);
assert.equal(buildProgress({weeklyChecklists:[{...plan,items:[{done:false}]}]},now).xp,0);
const auto={id:'pos',record_type:'position_review',timestamp:'2026-09-28T12:00:00',question:'Should I commit now?',line_a:'Commit to the battlefield.',line_b:'Hold for the following turn.',takeaway:'Preserve interaction against the plausible range.',review_status:'reviewed'};
assert.equal(buildProgress({notes:[auto]},now).xp,40);
assert.equal(buildProgress({notes:[{...auto,takeaway:''}]},now).xp,0);
assert.equal(buildProgress({notes:[a],weeklyChecklists:[{...plan,phase:'launch'}]},now).quests[2].kind,'discipline');
assert.equal(buildProgress({notes:[a]},new Date('2026-10-20T12:00:00')).xp,30,'rest days preserve XP');
console.log('Cultivation: 27 progression, correction, season, and evidence checks passed.');
